import { EmergencyContact } from "../types/contacts";

/**
 * DEMO OPERATIONAL & EMERGENCY CONTACT DIRECTORY
 * Note: These are simulated prototype contact details for the SIH hackathon demonstration.
 */
export const DEMO_CONTACTS: EmergencyContact[] = [
  {
    id: "cnt-01",
    role: "Central Control Room",
    department: "Mining Operations Control",
    contactPerson: "Control Room Operator On-Duty",
    phone: "+91 (080) 555-0101 / Ext: 101",
    radioChannel: "VHF Channel 1 (Mining Ops)",
    email: "control.room@nmdc-demo.internal",
    location: "Main Plant Tower - Floor 3",
    availableHours: "24/7 Continuous",
    priority: "emergency",
  },
  {
    id: "cnt-02",
    role: "Mechanical Maintenance",
    department: "Conveyor & Pulley Engineering",
    contactPerson: "Er. Rajesh Sharma (Lead Mechanical)",
    phone: "+91 98765-43210 / Ext: 204",
    radioChannel: "VHF Channel 3 (Mech Team)",
    email: "mech.maint@nmdc-demo.internal",
    location: "Workshop Bay B - Ore Processing",
    availableHours: "Shift 1 & 2 (24h On-Call)",
    priority: "operational",
  },
  {
    id: "cnt-03",
    role: "Electrical Maintenance",
    department: "Drive Motors & Power Systems",
    contactPerson: "Er. Priya Verma (Electrical In-Charge)",
    phone: "+91 98765-43211 / Ext: 205",
    radioChannel: "VHF Channel 4 (Electrical)",
    email: "elec.maint@nmdc-demo.internal",
    location: "Substation 02 - Drive Complex",
    availableHours: "Shift 1 & 2 (24h On-Call)",
    priority: "operational",
  },
  {
    id: "cnt-04",
    role: "Safety Officer",
    department: "Mine Safety & Inspection Bureau",
    contactPerson: "Col. S. K. Singh (Safety Lead)",
    phone: "+91 98765-43212 / Ext: 112",
    radioChannel: "VHF Channel 2 (Safety Priority)",
    email: "safety.officer@nmdc-demo.internal",
    location: "Safety & Compliance Building",
    availableHours: "24/7 Emergency Dispatch",
    priority: "emergency",
  },
  {
    id: "cnt-05",
    role: "Conveyor Line Supervisor",
    department: "Pit-to-Plant Conveyance Unit BC01",
    contactPerson: "V. R. Murthy (Shift Supervisor)",
    phone: "+91 98765-43213 / Ext: 301",
    radioChannel: "VHF Channel 1 (Mining Ops)",
    email: "supervisor.bc01@nmdc-demo.internal",
    location: "Conveyor Belt Corridor S2",
    availableHours: "Current Shift Lead",
    priority: "operational",
  },
  {
    id: "cnt-06",
    role: "Emergency Medical Team",
    department: "Mine Medical Center & First Response",
    contactPerson: "Dr. Ananya Ray (Chief Medical Officer)",
    phone: "+91 108 / +91 98765-00108",
    radioChannel: "VHF Channel 9 (Medical Priority)",
    email: "medical.center@nmdc-demo.internal",
    location: "On-Site First Aid Clinic - Sector A",
    availableHours: "24/7 Ambulance on Standby",
    priority: "emergency",
  },
  {
    id: "cnt-07",
    role: "Fire & Emergency Services",
    department: "Industrial Fire Brigade & Rescue",
    contactPerson: "Station Officer K. Patil",
    phone: "+91 101 / +91 98765-00101",
    radioChannel: "VHF Channel 8 (Fire & Rescue)",
    email: "fire.safety@nmdc-demo.internal",
    location: "Fire Station Post 1 - Main Yard",
    availableHours: "24/7 Rapid Response Unit",
    priority: "emergency",
  },
  {
    id: "cnt-08",
    role: "System Administrator",
    department: "IoT Infrastructure & SCADA Systems",
    contactPerson: "SIH Software Development Lead",
    phone: "+91 98765-43299 / Ext: 500",
    radioChannel: "VHF Channel 5 (IT Support)",
    email: "admin.iot@nmdc-demo.internal",
    location: "Server Room / IoT Lab",
    availableHours: "08:00 - 20:00 (On-Call)",
    priority: "support",
  },
];
