"use client";

import React from "react";
import { useTelemetry } from "@/lib/TelemetryContext";
import { Cpu, ShieldAlert, ShieldCheck, Activity } from "lucide-react";

export const AppHeader: React.FC = () => {
  const { health, backendError, isStale, isUnavailable, telemetry } = useTelemetry();

  const isMqttRequired = health?.mqtt_required ?? true;
  const isDbConnected = health?.database_connected ?? false;
  const isMqttConnected = health?.mqtt_connected ?? false;
  const isCloudDemo = health?.cloud_demo ?? (health?.data_source === "CLOUD_DEMO");

  const isConnectedOk = isDbConnected && (!isMqttRequired || isMqttConnected);

  const getSystemStatus = () => {
    if (backendError || !health) {
      return { label: "Software Offline", state: "offline", icon: ShieldAlert };
    }
    if (!isConnectedOk || isStale || isUnavailable) {
      return { label: "Software Degraded", state: "stale", icon: ShieldAlert };
    }
    return { label: "Platform Online", state: "online", icon: ShieldCheck };
  };

  const status = getSystemStatus();
  const StatusIcon = status.icon;
  const deviceId = telemetry?.device_id || health?.device_id || "ESP32-01";
  const isEsp32 = health?.data_source === "ESP32";

  const getDataSourceLabel = () => {
    if (isCloudDemo) {
      return "Prototype • Cloud Synthetic Telemetry";
    }
    if (isEsp32) {
      return "Hardware Mode • ESP32";
    }
    return "Prototype • Synthetic Telemetry";
  };

  return (
    <header className="main-header">
      <div className="header-left">
        <div className="header-title-block" style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <h1 className="header-title" style={{ fontSize: "1.2rem", fontWeight: 800, letterSpacing: "0.5px", color: "var(--text-main)", margin: 0 }}>
            SRIJAN
          </h1>
          <span className="header-divider" style={{ color: "var(--text-muted)" }}>/</span>
          <span className="header-subtitle" style={{ fontSize: "0.9rem", color: "var(--text-muted)", fontWeight: 500 }}>
            Conveyor Health Monitoring Platform
          </span>
          <span
            style={{
              fontSize: "0.725rem",
              fontWeight: 700,
              padding: "2px 8px",
              backgroundColor: "#e2e8f0",
              color: "#475569",
              borderRadius: "4px",
              letterSpacing: "0.5px",
            }}
          >
            SIH26008
          </span>
        </div>
      </div>

      <div className="header-right" style={{ display: "flex", alignItems: "center", gap: "10px" }}>
        {/* 1. SEPARATED DATA SOURCE BADGE */}
        <div
          className="disclosure-pill"
          title={
            isCloudDemo
              ? "FastAPI background continuous synthetic telemetry generator for public cloud presentation"
              : isEsp32
              ? "Receiving live telemetry from physical ESP32"
              : "Data generated by Python ESP32 simulator"
          }
        >
          <span className="pill-dot" />
          <span>{getDataSourceLabel()}</span>
        </div>

        {/* 2. SEPARATED ACTIVE SCENARIO BADGE */}
        <div
          className="device-pill"
          style={{ backgroundColor: "#f1f5f9", borderColor: "#cbd5e1" }}
          title="Active simulation scenario emitted by data source"
        >
          <Activity size={13} style={{ color: "var(--accent-primary)" }} />
          <span>Scenario: <strong>{telemetry?.scenario ? telemetry.scenario : "NORMAL"}</strong></span>
        </div>

        {/* 3. TARGET DEVICE BADGE */}
        <div className="device-pill">
          <Cpu size={14} className="device-icon" />
          <span>{isCloudDemo ? "Virtual Node:" : "Target:"} <strong>{deviceId}</strong></span>
        </div>

        {/* 4. SOFTWARE STACK CONNECTIVITY BADGE */}
        <div className={`status-pill ${status.state}`}>
          <StatusIcon size={14} />
          <span>{status.label}</span>
        </div>
      </div>
    </header>
  );
};

